name: Flask App CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          pip install flask opencv-python numpy pillow werkzeug

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Set up ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Flask App
        run: |
          python main.py &  # Flask must listen on 0.0.0.0:5000
          sleep 5

      - name: Start ngrok and print URL
        run: |
          ngrok http 5000 > /dev/null &
          sleep 5
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
