name: Flask App CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          pip install flask opencv-python numpy pillow werkzeug

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install LocalTunnel
        run: npm install -g localtunnel

      - name: Start Flask App
        run: python main.py &

      - name: Expose Flask App with LocalTunnel
        run: |
          lt --port 5000 > lt_output.txt &
          sleep 5
          cat lt_output.txt
